#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderB_redesign.Areas.admin.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.Web.Mvc;

	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tbrhsc")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmenu_category(menu_category instance);
    partial void Updatemenu_category(menu_category instance);
    partial void Deletemenu_category(menu_category instance);
    partial void InsertPage(Page instance);
    partial void UpdatePage(Page instance);
    partial void DeletePage(Page instance);
    #endregion
		
		public LinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["tbrhsc"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<menu_category> menu_categories
		{
			get
			{
				return this.GetTable<menu_category>();
			}
		}
		
		public System.Data.Linq.Table<Page> Pages
		{
			get
			{
				return this.GetTable<Page>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="team5.menu_categories")]
	public partial class menu_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _menu_id;
		
		private string _menu_text;
		
		private int _parent_id;
		
		private string _menu_slug;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmenu_idChanging(int value);
    partial void Onmenu_idChanged();
    partial void Onmenu_textChanging(string value);
    partial void Onmenu_textChanged();
    partial void Onparent_idChanging(int value);
    partial void Onparent_idChanged();
    partial void Onmenu_slugChanging(string value);
    partial void Onmenu_slugChanged();
    #endregion
		
		public menu_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int menu_id
		{
			get
			{
				return this._menu_id;
			}
			set
			{
				if ((this._menu_id != value))
				{
					this.Onmenu_idChanging(value);
					this.SendPropertyChanging();
					this._menu_id = value;
					this.SendPropertyChanged("menu_id");
					this.Onmenu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_text", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string menu_text
		{
			get
			{
				return this._menu_text;
			}
			set
			{
				if ((this._menu_text != value))
				{
					this.Onmenu_textChanging(value);
					this.SendPropertyChanging();
					this._menu_text = value;
					this.SendPropertyChanged("menu_text");
					this.Onmenu_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="Int NOT NULL")]
		public int parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_slug", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string menu_slug
		{
			get
			{
				return this._menu_slug;
			}
			set
			{
				if ((this._menu_slug != value))
				{
					this.Onmenu_slugChanging(value);
					this.SendPropertyChanging();
					this._menu_slug = value;
					this.SendPropertyChanged("menu_slug");
					this.Onmenu_slugChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pages")]
	public partial class Page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _page_id;
		
		private string _page_title;
		
		private int _user_id;
		
		private string _page_content;
		
		private System.DateTime _page_created;
		
		private int _menu_id;
		
		private char _page_visibility;
		
		private string _page_slug;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpage_idChanging(int value);
    partial void Onpage_idChanged();
    partial void Onpage_titleChanging(string value);
    partial void Onpage_titleChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onpage_contentChanging(string value);
    partial void Onpage_contentChanged();
    partial void Onpage_createdChanging(System.DateTime value);
    partial void Onpage_createdChanged();
    partial void Onmenu_idChanging(int value);
    partial void Onmenu_idChanged();
    partial void Onpage_visibilityChanging(char value);
    partial void Onpage_visibilityChanged();
    partial void Onpage_slugChanging(string value);
    partial void Onpage_slugChanged();
    #endregion
		
		public Page()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int page_id
		{
			get
			{
				return this._page_id;
			}
			set
			{
				if ((this._page_id != value))
				{
					this.Onpage_idChanging(value);
					this.SendPropertyChanging();
					this._page_id = value;
					this.SendPropertyChanged("page_id");
					this.Onpage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_title", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string page_title
		{
			get
			{
				return this._page_title;
			}
			set
			{
				if ((this._page_title != value))
				{
					this.Onpage_titleChanging(value);
					this.SendPropertyChanging();
					this._page_title = value;
					this.SendPropertyChanged("page_title");
					this.Onpage_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
        [AllowHtml]
		public string page_content
		{
			get
			{
				return this._page_content;
			}
			set
			{
				if ((this._page_content != value))
				{
					this.Onpage_contentChanging(value);
					this.SendPropertyChanging();
					this._page_content = value;
					this.SendPropertyChanged("page_content");
					this.Onpage_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_created", DbType="Date NOT NULL")]
		public System.DateTime page_created
		{
			get
			{
				return this._page_created;
			}
			set
			{
				if ((this._page_created != value))
				{
					this.Onpage_createdChanging(value);
					this.SendPropertyChanging();
					this._page_created = value;
					this.SendPropertyChanged("page_created");
					this.Onpage_createdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_id", DbType="Int NOT NULL")]
		public int menu_id
		{
			get
			{
				return this._menu_id;
			}
			set
			{
				if ((this._menu_id != value))
				{
					this.Onmenu_idChanging(value);
					this.SendPropertyChanging();
					this._menu_id = value;
					this.SendPropertyChanged("menu_id");
					this.Onmenu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_visibility", DbType="Char(1) NOT NULL")]
		public char page_visibility
		{
			get
			{
				return this._page_visibility;
			}
			set
			{
				if ((this._page_visibility != value))
				{
					this.Onpage_visibilityChanging(value);
					this.SendPropertyChanging();
					this._page_visibility = value;
					this.SendPropertyChanged("page_visibility");
					this.Onpage_visibilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_slug", DbType="VarChar(50)")]
		public string page_slug
		{
			get
			{
				return this._page_slug;
			}
			set
			{
				if ((this._page_slug != value))
				{
					this.Onpage_slugChanging(value);
					this.SendPropertyChanging();
					this._page_slug = value;
					this.SendPropertyChanged("page_slug");
					this.Onpage_slugChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
