<?xml version="1.0" encoding="utf-8"?><Database Name="tbrhsc" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=dodder.arvixe.com;Initial Catalog=tbrhsc;User ID=team5" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="tbrhsc" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Job" Member="Jobs">
    <Type Name="Job">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="job_title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="closing_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="job_description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="date_posted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Job_jobApplication" Member="jobApplications" ThisKey="Id" OtherKey="job_id" Type="jobApplication" />
      <Association Name="jobCategory_Job" Member="jobCategory" ThisKey="category_id" OtherKey="Id" Type="jobCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.departments" Member="departments">
    <Type Name="department">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dept_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dept_description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="department_doctor" Member="doctors" ThisKey="id" OtherKey="dept_id" Type="doctor" />
      <Association Name="department_doctor1" Member="doctors1" ThisKey="id" OtherKey="dept_id" Type="doctor" />
    </Type>
  </Table>
  <Table Name="dbo.product_category" Member="product_categories">
    <Type Name="product_category">
      <Column Name="prd_cat_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prd_cat_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="product_category_product" Member="products" ThisKey="prd_cat_id" OtherKey="prd_cat_id" Type="product" />
    </Type>
  </Table>
  <Table Name="team5.menu_categories" Member="menu_categories">
    <Type Name="menu_category">
      <Column Name="menu_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="menu_text" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="menu_slug" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="menu_category_menu_category" Member="menu_categories" ThisKey="menu_id" OtherKey="parent_id" Type="menu_category" />
      <Association Name="menu_category_page" Member="pages" ThisKey="menu_id" OtherKey="menu_id" Type="page" />
      <Association Name="menu_category_menu_category" Member="menu_category1" ThisKey="parent_id" OtherKey="menu_id" Type="menu_category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.triage" Member="triages">
    <Type Name="triage">
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="patient_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="arrival" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="discharge" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="em_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dr_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="doctor_triage" Member="doctor" ThisKey="dr_id" OtherKey="dr_id" Type="doctor" IsForeignKey="true" />
      <Association Name="doctor_triage1" Member="doctor1" ThisKey="dr_id" OtherKey="dr_id" Type="doctor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AlertTable" Member="AlertTables">
    <Type Name="AlertTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="alert" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="colour" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="alertNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.faq" Member="faqs">
    <Type Name="faq">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="question" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="answer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.donation" Member="donations">
    <Type Name="donation">
      <Column Name="dtn_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dtn_dnr_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtn_amount" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="dtn_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="donor_donation" Member="donor" ThisKey="dtn_dnr_id" OtherKey="dnr_id" Type="donor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.feedbacks" Member="feedbacks">
    <Type Name="feedback">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="topic" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fbcontent" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.emergency_levels" Member="emergency_levels">
    <Type Name="emergency_level">
      <Column Name="em_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="em_description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="em_duration_hrs" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.subscriber" Member="subscribers">
    <Type Name="subscriber">
      <Column Name="sub_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sub_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sub_email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.jobCategory" Member="jobCategories">
    <Type Name="jobCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Association Name="jobCategory_Job" Member="Jobs" ThisKey="Id" OtherKey="category_id" Type="Job" />
    </Type>
  </Table>
  <Table Name="dbo.jobApplication" Member="jobApplications">
    <Type Name="jobApplication">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="job_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="cover_letter" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="resume" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="date_posted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Job_jobApplication" Member="Job" ThisKey="job_id" OtherKey="Id" Type="Job" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.appointments" Member="appointments">
    <Type Name="appointment">
      <Column Name="apt_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dr_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date_req" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="date_book" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="time_book" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pat_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pat_phone" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="pat_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="app_status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="doctor_appointment" Member="doctor" ThisKey="dr_id" OtherKey="dr_id" Type="doctor" IsForeignKey="true" />
      <Association Name="doctor_appointment1" Member="doctor1" ThisKey="dr_id" OtherKey="dr_id" Type="doctor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.newsTable" Member="newsTables">
    <Type Name="newsTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="stories" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="headline" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Volunteer" Member="Volunteers">
    <Type Name="Volunteer">
      <Column Name="volunteer_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="phone" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Volunteer_Shift" Member="Shifts" ThisKey="volunteer_id" OtherKey="volunteer_id" Type="Shift" />
    </Type>
  </Table>
  <Table Name="dbo.pages" Member="pages">
    <Type Name="page">
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="page_title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="page_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="page_created" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="menu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="page_visibility" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="page_slug" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="meta_title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="meta_desc" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="page_order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="menu_category_page" Member="menu_category" ThisKey="menu_id" OtherKey="menu_id" Type="menu_category" IsForeignKey="true" DeleteRule="SET DEFAULT" />
    </Type>
  </Table>
  <Table Name="dbo.Shifts" Member="Shifts">
    <Type Name="Shift">
      <Column Name="shift_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="volunteer_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="day" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="shifts" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Volunteer_Shift" Member="Volunteer" ThisKey="volunteer_id" OtherKey="volunteer_id" Type="Volunteer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="team5.webpages_UsersInRoles" Member="webpages_UsersInRoles">
    <Type Name="webpages_UsersInRole">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="webpages_Role_webpages_UsersInRole" Member="webpages_Role" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="team5.webpages_Roles" Member="webpages_Roles">
    <Type Name="webpages_Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="webpages_Role_webpages_UsersInRole" Member="webpages_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.donor" Member="donors">
    <Type Name="donor">
      <Column Name="dnr_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dnr_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dnr_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dnr_phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dnr_apt_no" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dnr_street" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dnr_city" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dnr_province" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dnr_country" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dnr_postal_code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="donor_donation" Member="donations" ThisKey="dnr_id" OtherKey="dtn_dnr_id" Type="donation" />
    </Type>
  </Table>
  <Table Name="dbo.volshift" Member="volshifts">
    <Type Name="volshift">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="shiftday" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="prd_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prd_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prd_description" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="prd_price" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="prd_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prd_cat_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prd_img_url" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="product_category_product" Member="product_category" ThisKey="prd_cat_id" OtherKey="prd_cat_id" Type="product_category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.doctors" Member="doctors">
    <Type Name="doctor">
      <Column Name="dr_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dr_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dr_specialty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dr_office_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dr_office_address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="dr_office_phone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dept_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="doctor_triage" Member="triages" ThisKey="dr_id" OtherKey="dr_id" Type="triage" />
      <Association Name="doctor_triage1" Member="triages1" ThisKey="dr_id" OtherKey="dr_id" Type="triage" />
      <Association Name="doctor_appointment" Member="appointments" ThisKey="dr_id" OtherKey="dr_id" Type="appointment" />
      <Association Name="doctor_appointment1" Member="appointments1" ThisKey="dr_id" OtherKey="dr_id" Type="appointment" />
      <Association Name="department_doctor" Member="department" ThisKey="dept_id" OtherKey="id" Type="department" IsForeignKey="true" />
      <Association Name="department_doctor1" Member="department1" ThisKey="dept_id" OtherKey="id" Type="department" IsForeignKey="true" />
    </Type>
  </Table>
</Database>