#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderB_redesign.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tbrhsc")]
	public partial class MenuLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmenu_category(menu_category instance);
    partial void Updatemenu_category(menu_category instance);
    partial void Deletemenu_category(menu_category instance);
    #endregion
		
		public MenuLinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["tbrhsc"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MenuLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<menu_category> menu_categories
		{
			get
			{
				return this.GetTable<menu_category>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="team5.menu_categories")]
	public partial class menu_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _menu_id;
		
		private string _menu_text;
		
		private int _parent_id;
		
		private string _menu_slug;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmenu_idChanging(int value);
    partial void Onmenu_idChanged();
    partial void Onmenu_textChanging(string value);
    partial void Onmenu_textChanged();
    partial void Onparent_idChanging(int value);
    partial void Onparent_idChanged();
    partial void Onmenu_slugChanging(string value);
    partial void Onmenu_slugChanged();
    #endregion
		
		public menu_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int menu_id
		{
			get
			{
				return this._menu_id;
			}
			set
			{
				if ((this._menu_id != value))
				{
					this.Onmenu_idChanging(value);
					this.SendPropertyChanging();
					this._menu_id = value;
					this.SendPropertyChanged("menu_id");
					this.Onmenu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_text", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string menu_text
		{
			get
			{
				return this._menu_text;
			}
			set
			{
				if ((this._menu_text != value))
				{
					this.Onmenu_textChanging(value);
					this.SendPropertyChanging();
					this._menu_text = value;
					this.SendPropertyChanged("menu_text");
					this.Onmenu_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="Int NOT NULL")]
		public int parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_slug", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string menu_slug
		{
			get
			{
				return this._menu_slug;
			}
			set
			{
				if ((this._menu_slug != value))
				{
					this.Onmenu_slugChanging(value);
					this.SendPropertyChanging();
					this._menu_slug = value;
					this.SendPropertyChanged("menu_slug");
					this.Onmenu_slugChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
